#!/usr/bin/env python3
"""RED proof for smoke_the_machine_holds_off_the_happy_path.

Six mutations, one per property the consolidated pass of 2026-09-17 added:
the microsecond read, the derived span, the segmenter's length split, the
lifted withhold, the plan-keyed hops, and the withheld Skill tool. The first
four hit DRIVEN legs — the mutant changes a return value, not a sentence.
"""
import ast
import io
import os
import json
import glob
import re
import subprocess
import sys

sys.path.insert(0, ".")
import red_proof_anchor as RA                                   # noqa: E402

TARGET = "chatcut_job_app.py"
SMOKE = "smoke_the_machine_holds_off_the_happy_path.py"

MUTATIONS = [
    ("sourceRange is read as milliseconds",
     '            a, b = float(sr["start"]) / 1e6, float(sr["end"]) / 1e6',
     '            a, b = float(sr["start"]) / 1e3, float(sr["end"]) / 1e3',
     "kept_spans reads sourceRange{start,end} in microseconds",
     'float(sr["start"]) / 1e6'),
    ("a missing sourceRange fails instead of deriving",
     '            if not sr:\n                a, b = 0.0, (f1 - f0) / float(fps or 30.0)',
     '            if False:\n                a, b = 0.0, (f1 - f0) / float(fps or 30.0)',
     "an untrimmed item with NO sourceRange is DERIVED, not failed",
     "if not sr:"),
    ("the segmenter stops splitting long runs",
     '        if gap >= gap_s or span > max_beat_s:',
     '        if gap >= gap_s:',
     "86 words over a ~20s narration become 7-10 beats",
     "span > max_beat_s"),
    ("plan-keyed hops fail the chain again",
     '    _plan_hops = () if plan else ("hop3", "hop4")',
     '    _plan_hops = ()',
     "plan-keyed hops are N/A on the single-agent path, not failures",
     '_plan_hops = () if plan else ("hop3", "hop4")'),
    # TWO MUTATIONS, TWO LEGS. Skipping the string branch makes a prose
    # treatment yield [] — which the "never characters" leg accepts — so that
    # mutant is aimed at the leg it actually breaks (the families it names),
    # and the character iteration is reintroduced by letting a str fall into
    # the list branch, which is exactly the shape that produced 2,648 withholds.
    # VACUOUS the first time: letting a str fall into the list branch changed
    # nothing, because the str branch above it catches strings first. The
    # honest mutation removes the FAMILY FILTER — then the run's own prose
    # ("caption:TwoTone only. There's no screenshot...") yields 'only',
    # 'there', 's', 'no'... and the leg that expects [] goes red.
    ("the family filter on a prose treatment is removed",
     '        fams = [x for x in toks if x in KNOWN_FAMILIES]',
     '        fams = toks',
     "a prose treatment yields families, never characters",
     "fams = [x for x in toks if x in KNOWN_FAMILIES]"),
    ("the string branch stops naming families",
     '    if isinstance(t, str):\n        import re as _re',
     '    if False:\n        import re as _re',
     "...and names the families it does contain",
     "if isinstance(t, str):"),
    ("the base item echo goes back to the raw envelope",
     '                _ar = _mcp_call(access_token, "edit_item",\n                                {"projectId": pid, "adds": [_add]}, expect="adds")',
     '                _ar = call("edit_item", {"projectId": pid, "adds": [_add]}, 23)',
     "the base item's echo is parsed (expect='adds'), not read off the envelope",
     'expect="adds")'),
    ("the ceiling counts every event again",
     '        if _mid in _seen:\n            return 0\n        _seen.add(_mid)',
     '        if False:\n            return 0\n        _seen.add(_mid)',
     "the ceiling counts a message id once, however many events carry it",
     "if _mid in _seen:"),
    ("the ledger sums every event again",
     '        if _mid and _mid in _seen_ids:\n            continue',
     '        if False:\n            continue',
     "the ledger's cache sums are deduped by message id",
     "if _mid and _mid in _seen_ids:"),
    ("the tool block stops being restricted at the flag",
     '             "--tools", _sel,',
     '             "--tools", _sel + ",mcp__chatcut__read_project",',
     "--tools restricts the block to the agent's surface, and that surface is the edit ops",
     '"--tools", _sel,'),
    ("only the first result event is billed again",
     '    _results = [e for e in ev if e.get("type") == "result" and e.get("result_usage")]',
     '    _results = [e for e in ev if e.get("type") == "result" and e.get("result_usage")][:1]',
     "the bill sums every result event, one per user turn",
     '_results = [e for e in ev if e.get("type") == "result"'),
    # AIMED AT THE FUNCTION THE LEG DRIVES: the leg calls slim_tool directly,
    # so a mutation to its caller cannot bite (NOT RED the first time).
    ("the shim keeps the tool description",
     '    out = {"name": t.get("name"), "description": t.get("name", "").replace("_", " "),',
     '    out = {"name": t.get("name"), "description": t.get("description") or t.get("name", ""),',
     "the shim cuts a tool to name and arguments",
     '"description": t.get("name", "").replace("_", " ")'),
    ("the source watch samples one call of frames",
     '    for ci in range(0, len(times), 25):',
     '    for ci in range(0, min(len(times), 25), 25):',
     "the source is watched through inspect_asset: 40 exact frames at 2fps in two calls",
     "for ci in range(0, len(times), 25):"),
    ("the record Write comes back to the paragraph",
     '            "\\"propertyOverrides\\": {...}, \\"why\\": \\"under 12 words\\"}. "',
     '            "\\"propertyOverrides\\": {...}}. Then Write /work/record.json as one line per item you placed. "',
     "the paragraph asks for the why inside each op, and for no record",
     '\\"why\\": \\"under 12 words\\"'),
    # AIMED AT THE LIVE BRANCH: the loop never REQUESTS a fifth turn, so the
    # `if n > cap` guard is defensive and a mutation there is vacuous (NOT RED
    # the first time). The cap that fires on a runaway is the contingency
    # turn's own branch: fix ops at turn 4 are terminal.
    ("a third call is added to the machine",
     '    r2 = _turn(2, (rw1 or {}).get("message"), "review")',
     '    r2 = _turn(2, (rw1 or {}).get("message"), "review")\n    _turn(3, None, "extra")',
     "THE CAP IS STRUCTURAL: the machine only ever makes two calls, so a third cannot be requested",
     '_turn(2, (rw1 or {}).get("message"), "review")'),
    ("the cache gate accepts any read",
     '    return r >= fraction * prefix, "read %d against %.2f x %d" % (r, fraction, prefix)',
     '    return True, "read %d against %.2f x %d" % (r, fraction, prefix)',
     "a call that does not read the prefix call 1 established is terminal",
     'return r >= fraction * prefix'),
    ("an empty timeline stops being a fault",
     '    if not placed and brief_mode == "full_edit":',
     '    if False:',
     "an empty timeline on a full-edit brief is a fault the agent is told",
     'if not placed and brief_mode == "full_edit":'),
    ("a placement-less turn 1 gets a second try",
     '    if not _edit_ops(r1.get("tool_calls")):\n        # TERMINAL AND LEDGERED',
     '    if False:\n        # TERMINAL AND LEDGERED',
     "turn 1 without an edit op is terminal, not a second try — even when it ends in a proper finish call",
     'tm["terminal"] = {"kind": "NO PLACEMENT", "at": 1,'),
    ("the invocation waits for a next message that never comes",
     '                _res.update(ev)\n                # THE TURN IS OVER WHEN THE RESULT ARRIVES.',
     '                _res.update(ev)\n                return\n                # THE TURN IS OVER WHEN THE RESULT ARRIVES.',
     "each invocation closes stdin when the result event arrives",
     '_res.update(ev)'),
    ("the reference instrument is unmounted again",
     '    .add_local_file(os.path.join(_HERE, "chatcut_reference.py"),\n                    "/root/chatcut_reference.py", copy=True)\n',
     '',
     "every lane module imported at run time is mounted in the image",
     '"/root/chatcut_reference.py"'),
    ("the reader goes back to json.loads (JSON-then-prose raises again)",
     "                parsed, _endpos = json.JSONDecoder().raw_decode(t.strip())",
     "                parsed, _endpos = json.loads(t.strip()), 0",
     "a JSON-then-prose edit_item envelope parses (four landed plants read as 'no adds')",
     "raw_decode(t.strip())"),
    ("--effort is dropped from the invocation",
     '            + (["--effort", str(effort)] if effort else [])\n',
     '',
     "--effort <level> is sent when given and absent otherwise",
     '"--effort", str(effort)'),
    ("the rewatch pays for an export again",
     "            _sheets, _times = _preview_frames(tok, _stage[\"projectId\"], _end, fps=float(_rb.get(\"fps\") or 30), density_fps=density_fps,\n                                              mark=lambda k: mark(\"rewatch%d.%s\" % (n, k)))",
     "            _sheets, _times = _edit_frames(tok, _stage[\"projectId\"], _end, mark=lambda k: mark(\"rewatch%d.%s\" % (n, k)))",
     "the rewatch watches through preview_timeline, never the export (paid once, for the final)",
     "_preview_frames(tok, _stage["),
    ("5-minute writes are priced as 1-hour writes",
     "    _usd = (_rd * 0.30 + _wr5 * 3.75 + (_wr - _wr5) * 6.00 + _in * 3.00 + _ou * 15.00) / 1e6",
     "    _usd = (_rd * 0.30 + _wr5 * 6.00 + (_wr - _wr5) * 6.00 + _in * 3.00 + _ou * 15.00) / 1e6",
     "cache writes are priced 5m at $3.75/M and the rest at $6/M, by the measured split",
     "_wr5 * 3.75"),
    ("the TTL split is no longer recorded per call",
     '                         "write_1h": (u.get("cache_creation") or {}).get("ephemeral_1h_input_tokens"),\n                         "write_5m": (u.get("cache_creation") or {}).get("ephemeral_5m_input_tokens")},',
     '                         },',
     "every API call records which TTL it wrote (write_1h / write_5m)",
     '"write_5m": (u.get("cache_creation")'),
    ("a planted label carries the detector's word again",
     '             "propertyOverrides": {"label": "REVENUE", "value": "10x", "offsetY": 0}},',
     '             "propertyOverrides": {"label": "ON THE FACE", "value": "10x", "offsetY": 0}},',
     "the planted labels contain none of the detector's words (the first probe scored its own labels)",
     '"label": "REVENUE"'),
    ("the CLI version is no longer read in the job",
     '    _cli_ver = cli_version()\n',
     '    _cli_ver = "unread"\n',
     "cli_version reads `claude --version` in the container and names a failure; edit and keep_warm both record it",
     "_cli_ver = cli_version()"),
    ("the upstream leg goes untraced again",
     "        finally:\n            conn.close()\n            _trace(row)",
     "        finally:\n            conn.close()",
     "every upstream leg is traced: status, first byte, bytes relayed, redacted key",
     "_trace(row)"),
    ("a 5-minute ping is treated as an hour",
     '    if int(warm_rec.get("write_5m") or 0) > 0:\n        return 5',
     '    if int(warm_rec.get("write_5m") or 0) > 0:\n        return 60',
     "a ping's TTL is read from what it wrote: 1h -> 60 min, 5m -> 5 min, no split -> unknown",
     'return 5'),
    ("the cold-write verdict goes back to a literal hour",
     '" — a DEFECT, the ping was alive" if (_mins is not None and _ttl and _mins < _ttl) else ""',
     '" — a DEFECT, the ping was alive" if (_mins is not None and _ttl and _mins < 60) else ""',
     "the cold-write defect verdict compares against the ping's own TTL",
     "_mins < _ttl"),
    ("the CLI install is unpinned again",
     '        "npm install -g @anthropic-ai/claude-code@" + CLI_PIN,',
     '        "npm install -g @anthropic-ai/claude-code",',
     "the image installs a PINNED claude-code (name@CLI_PIN), and the pin is a version",
     'claude-code@" + CLI_PIN'),
    ("the job goes back to ANTHROPIC_BASE_URL",
     '        _env.update(_px.mitm_env(_px_port, _px_ca))\n',
     '        _env["ANTHROPIC_BASE_URL"] = "http://127.0.0.1:%d" % _px_port\n',
     "the job starts the transparent proxy and never names ANTHROPIC_BASE_URL",
     "_env.update(_px.mitm_env(_px_port, _px_ca))"),
    ("the CA is no longer handed to the CLI",
     '            "NODE_EXTRA_CA_CERTS": ca_pem}',
     '            }',
     "the CLI is routed by HTTPS_PROXY + NODE_EXTRA_CA_CERTS, never by ANTHROPIC_BASE_URL",
     '"NODE_EXTRA_CA_CERTS": ca_pem'),
    ("CONNECT is answered without TLS termination",
     "        self.send_response(200, \"Connection established\")",
     "        self.send_response(502, \"Connection refused\")",
     "a CONNECT to api.anthropic.com is terminated with the throwaway CA, recorded, fingerprinted and relayed",
     '"Connection established"'),
    ("the shim keeps the tunnel it inherited",
     "def main():\n    scrub_proxy_env(os.environ)",
     "def main():\n    pass",
     "the shim scrubs the proxy variables it inherits before its first ChatCut call (5 tools instead of 13 on the tunnelled ping)",
     "scrub_proxy_env(os.environ)"),
    ("NO_PROXY no longer names the ChatCut host",
     '"NO_PROXY": "api.chatcut.io,localhost,127.0.0.1", "no_proxy": "api.chatcut.io,localhost,127.0.0.1",',
     '"NO_PROXY": "localhost,127.0.0.1", "no_proxy": "localhost,127.0.0.1",',
     "the CLI is routed by HTTPS_PROXY + NODE_EXTRA_CA_CERTS, never by ANTHROPIC_BASE_URL",
     '"NO_PROXY": "api.chatcut.io'),
    ("a per-turn constant kills the turn again",
     "            _cmd_n + [\"--max-turns\", \"1\"], \"/work\", _stream, _tfile, _left,",
     "            _cmd_n + [\"--max-turns\", \"1\"], \"/work\", _stream, _tfile, 120,",
     "a turn's bound is what is left of the RUN budget, never a per-turn constant",
     "_stream, _tfile, _left,"),
    ("the wire's thinking field is no longer recorded",
     '    row["request_fields"] = {"thinking": body.get("thinking"), "output_config": body.get("output_config"),',
     '    row["request_fields"] = {"thinking": None, "output_config": body.get("output_config"),',
     "every fingerprint row carries what was sent beside the prefix: thinking, effort, max_tokens",
     '"thinking": body.get("thinking")'),
    ("the off arm goes back to the env var that only omits the field",
     '        _env = {"MAX_THINKING_TOKENS": "0"}',
     '        _env = {"CLAUDE_CODE_DISABLE_THINKING": "1"}',
     "think_tokens=0 sends MAX_THINKING_TOKENS=0 (wire: thinking disabled), never the env var that only omits the field",
     '_env = {"MAX_THINKING_TOKENS": "0"}'),
    ("the paragraph loses the add shape",
     '            "exactly this shape: {\\"type\\": \\"motion-graphic\\", \\"assetId\\": "',
     '            "exactly the usual shape: {\\"kind\\": \\"graphic\\", \\"assetId\\": "',
     "the deciding paragraph shows the exact add shape with the dieted why, names type motion-graphic, forbids the json field, routes captions to edit_captions, and never mentions /work/DONE",
     'exactly this shape: {\\"type\\": \\"motion-graphic\\"'),
    ("sheets go back to PNG",
     '        fp = os.path.join(out_dir, "sheet_%02d.jpg" % (len(out) + 1))\n        sheet.convert("RGB").save(fp, "JPEG", quality=85, optimize=True)',
     '        fp = os.path.join(out_dir, "sheet_%02d.png" % (len(out) + 1))\n        sheet.save(fp, "PNG", optimize=True)',
     "a 20-frame sheet is JPEG under 400 KB (PNG sheets at ~1.5 MB pushed call 4 past the 32 MB request limit)",
     'sheet.convert("RGB").save(fp, "JPEG"'),
    ("the json escape hatch is offered again",
     'HIDDEN_PROPS = {"json"}',
     'HIDDEN_PROPS = set()',
     "the slimmed edit_item schema does not offer `json`, and a json-string call is unwrapped into real fields",
     'HIDDEN_PROPS = {"json"}'),
    ("the shim strips whys without unwrapping the json string",
     '        args, unwrapped = unwrap_json_arg(args) if name == "edit_item" else (args, False)',
     '        unwrapped = False',
     "the shim unwraps before it strips the whys (the strip sees the real ops)",
     'unwrap_json_arg(args) if name == "edit_item"'),
    ("the billing header goes back into the system hash",
     '    sys_hashed = [b for b in system if not _is_billing(b)] if isinstance(system, list) else system',
     '    sys_hashed = system',
     "the billing-header block is outside the system hash and counted; the first differing message is reported even when the system differs",
     'if not _is_billing(b)'),
    ("the system prompt asks for the record files again",
     '        "You write no files. The record is read back from the timeline; the "',
     '        "WRITE /work/spec.json BEFORE YOU FINISH, then /work/DONE. The record is read back from the timeline; the "',
     "the no-preview sentence sits where the placement is decided, and no DONE mark is asked for anywhere the agent reads",
     '"You write no files. The record is read back'),
    ("the proxy stops placing the watch-end breakpoint",
     '    tail[-1]["cache_control"] = {"type": "ephemeral", "ttl": "1h"}',
     '    pass',
     "the proxy marks the watch's last block with a 1h breakpoint, raises the system markers to 1h, drops the CLI's second-to-last message marker, and stays within four",
     'tail[-1]["cache_control"] = {"type": "ephemeral", "ttl": "1h"}'),
    ("the system markers stay 5-minute (a 1h entry after them is refused)",
     '                x["cache_control"] = {**x["cache_control"], "ttl": "1h"}',
     '                x["cache_control"] = {**x["cache_control"]}',
     "the proxy marks the watch's last block with a 1h breakpoint, raises the system markers to 1h, drops the CLI's second-to-last message marker, and stays within four",
     '"ttl": "1h"}\n                raised += 1'),
    ("the rewritten body is fingerprinted but the original goes upstream",
     '                if inj.get("injected") or pinned:\n                    raw = json.dumps(body).encode("utf-8")',
     '                if inj.get("injected") or pinned:\n                    pass',
     "upstream receives the REWRITTEN body and the fingerprint row records the breakpoint",
     'raw = json.dumps(body).encode("utf-8")'),
    ("a 4xx from the API reads as the agent placing nothing",
     '        if isinstance(r.get("api_status"), int) and r["api_status"] >= 400:',
     '        if isinstance(r.get("api_status"), int) and r["api_status"] >= 600:',
     "a 4xx from the API is the terminal API ERROR at that turn, carrying the status and the API's words, and is never retried",
     'r["api_status"] >= 400'),
    ("the untouched source is exported after a terminal again",
     '    if _tm.get("terminal"):\n        _export = {"state": "WITHHELD"',
     '    if False:\n        _export = {"state": "WITHHELD"',
     "the export is WITHHELD after any terminal (the floor once exported the untouched source after a 400)",
     '_export = {"state": "WITHHELD"'),
    ("the job hands the proxy a text its first message does not carry",
     'RUN_FIRST_TEXT_JOB = "THE COMPONENT INVENTORY"',
     'RUN_FIRST_TEXT_JOB = "THE SOURCE FOOTAGE"',
     "job and ping both hand the proxy their run-first text, and the job's first message really starts with it",
     'RUN_FIRST_TEXT_JOB = "THE COMPONENT INVENTORY"'),
    ("development runs inject the 1h breakpoint too",
     '        _px.RUN_FIRST_TEXT = RUN_FIRST_TEXT_JOB if (prefix_ttl == "1h" and not no_watch) else ""',
     '        _px.RUN_FIRST_TEXT = RUN_FIRST_TEXT_JOB if not no_watch else ""',
     "the job hands the proxy its run-first text only at prefix_ttl 1h (development: 5m, no injection)",
     'if (prefix_ttl == "1h" and not no_watch) else ""'),
    ("the no-watch run resumes the watch anyway",
     '    _watch_sid = None if no_watch else install_watch("/work")',
     '    _watch_sid = install_watch("/work")',
     "no_watch skips the resume (no --resume in the command), skips the watch-end breakpoint, and the record says so",
     'None if no_watch else install_watch("/work")'),
    ("the export returns before the file is fetched",
     '        if not url:\n            return out\n        if mark: mark("export.render")',
     '        if not url:\n            return out\n        return out\n        if mark: mark("export.render")',
     "harness_export polls to the file, downloads it, and keeps bytes + sha beside the record",
     'import urllib.request as _ur, hashlib as _hl'),
    ("any role can be the run's first message again",
     '        if m.get("role") != "user":\n            continue\n        c = m.get("content")',
     '        c = m.get("content")',
     "only user-role messages count and the LAST match is the run's first message (a system-role 'skipping' once stole the mark)",
     'if m.get("role") != "user":'),
    ("request MB goes back to the record field that is empty when it is read",
     '    _req_mb = [round(float(x.get("req_bytes") or 0) / 1e6, 2) for x in _read_trace_rows() if isinstance(x, dict)',
     '    _req_mb = [round(float(x.get("req_bytes") or 0) / 1e6, 2) for x in (out.get("proxy_trace") or []) if isinstance(x, dict)',
     "request MB per call is read from the trace file, not from a record field built later (it printed [] on every run)",
     'for x in _read_trace_rows() if isinstance(x, dict)'),
    ("the system blocks are no longer named",
     '                      "block_shas": [(_sha(b)[0], _sha(b)[1], (b.get("text", "")[:60] if isinstance(b, dict) else ""))',
     '                      "block_shas": [(_sha(b)[0], _sha(b)[1], "")',
     "the fingerprint names every system block's sha and size (the billing header excluded)",
     '(b.get("text", "")[:60] if isinstance(b, dict) else "")'),
    ("the preflight passes a differing block",
     "        if a != b:\n            k = next(",
     "        if False:\n            k = next(",
     "the preflight passes an identical system (billing header aside), refuses a one-byte difference naming block and offset, and is skipped without a ping",
     "        if a != b:\n            k = next("),
    ("the refused call is forwarded anyway",
     "                        self.wfile.write(msg); self.wfile.flush()\n                        return",
     "                        self.wfile.write(msg); self.wfile.flush()",
     "a differing call 1 is answered 409 preflight_refused and never forwarded (no cold write paid)",
     "self.wfile.write(msg); self.wfile.flush()\n                        return"),
    ("the OS line is left to the fleet",
     '            new = _OS_RE.sub(r"\\1pinned", blk["text"])',
     '            new = blk["text"]',
     "the OS line is pinned to a constant so the fleet's kernel string cannot vary the prefix",
     '_OS_RE.sub(r"\\1pinned"'),
    ("call 2 exports without the harness reading the timeline back",
     '    rb = list(readback() or []) if readback else []',
     '    rb = []',
     "THE HARNESS'S READ-BACK OF THE FINISHED TIMELINE DECIDES: a fault there is terminal and refunded, never exported",
     'rb = list(readback() or []) if readback else []'),
    ("the platter repeats the shared keys per component",
     '        keys = ["%s (%s, e.g. %s)" % (p.get("key"), p.get("type"), json.dumps(p.get("defaultValue"))[:24]) for p in props if isinstance(p, dict) and p.get("key") and p.get("key") not in common]',
     '        keys = ["%s (%s, e.g. %s)" % (p.get("key"), p.get("type"), json.dumps(p.get("defaultValue"))[:24]) for p in props if isinstance(p, dict) and p.get("key")]',
     "the platter lists every registry component with the keys ChatCut accepts, the shared keys said once, EndCard end-only",
     'and p.get("key") not in common]'),
    ("the first message drops the platter",
     '        if platter:\n            blocks.append({"type": "text", "text": platter})',
     '        if False:\n            blocks.append({"type": "text", "text": platter})',
     "the first message carries the platter and the face lines",
     '        if platter:\n            blocks.append({"type": "text", "text": platter})'),
    ("the probe review is killed below the run bound again",
     '"/work/probe_%s_timing.json" % tag, RUN_TIMEOUT_S, env=env, stdin_first=json.dumps(msg), on_event=_on)',
     '"/work/probe_%s_timing.json" % tag, 180, env=env, stdin_first=json.dumps(msg), on_event=_on)',
     "every CLI invocation is bounded by the run bound or what is left of it, never a smaller number",
     '"/work/probe_%s_timing.json" % tag, RUN_TIMEOUT_S'),
    ("the preflight ignores a thinking mismatch",
     "        if mine != theirs:\n            return False,",
     "        if False:\n            return False,",
     "the preflight refuses a job whose thinking differs from the ping's (the API drops message entries on that change) and passes a match",
     "        if mine != theirs:"),
    ("the ping sends adaptive thinking for the off arm again",
     '    env = {"ENABLE_TOOL_SEARCH": "false", "MAX_THINKING_TOKENS": "0" if think_tokens == 0 else str(think_tokens if think_tokens > 0 else DEFAULT_THINK_TOKENS)}',
     '    env = {"ENABLE_TOOL_SEARCH": "false", "MAX_THINKING_TOKENS": str(DEFAULT_THINK_TOKENS)}',
     "the ping takes think_tokens and effort, sends MAX_THINKING_TOKENS=0 for the off arm, and passes effort to the command",
     '"0" if think_tokens == 0 else'),
    ("the machine's clock starts at turn 1 again",
     "    _tm = run_two_calls(_invoke, _rewatch, _first_message, t0=t0, verify=_verify,",
     "    _tm = run_two_calls(_invoke, _rewatch, _first_message, verify=_verify,",
     "edit() hands the machine the job's own t0",
     "run_two_calls(_invoke, _rewatch, _first_message, t0=t0, verify=_verify,"),
    ("the source watch goes back to the serial 60s fetch",
     '    got, ftiming = (fetch or fetch_frames)(urls[:len(times) + 5], out_dir, name="s")',
     '    got, fst0 = _cr.fetch(urls, out_dir, cap=len(times) + 5); ftiming = {"got": len(got), "n": len(urls), "wall_s": 0, "p50_s": 0, "max_s": 0, "failed": 0}',
     "the source watch and the rewatch both fetch through fetch_frames (never the serial 60s fetch)",
     '(fetch or fetch_frames)(urls[:len(times) + 5]'),
    ("the fetch bound goes back to a minute",
     "FETCH_TIMEOUT_S = 15",
     "FETCH_TIMEOUT_S = 60",
     "the default fetch bound is 15s, not 60",
     "FETCH_TIMEOUT_S = 15"),
    ("the asset id is read from the leading object only again",
     '    txt = str(envelope.get("_text") or "")\n    m = re.search(',
     '    txt = ""\n    m = re.search(',
     "asset_id_from finds a nested assetId, an assetId in the prose after the JSON, and names nothing when there is none",
     'txt = str(envelope.get("_text") or "")'),
    ("a None id counts as registered again",
     '            if not _aid_:\n                return _n, None, ["registered without an id',
     '            if False:\n                return _n, None, ["registered without an id',
     "a registration without an id is returned as a refusal, never counted as registered",
     '            if not _aid_:'),
    ("the CLI's retry of a refused call goes upstream",
     '                elif PREFLIGHT_REFUSED is not None:\n                    ok, rep_ = False, {**PREFLIGHT_REFUSED, "state": "REFUSED AGAIN (the CLI retried)"}',
     '                elif False:\n                    ok, rep_ = False, {**PREFLIGHT_REFUSED, "state": "REFUSED AGAIN (the CLI retried)"}',
     "a refused preflight refuses the CLI's retry too, and nothing ever reaches upstream",
     'elif PREFLIGHT_REFUSED is not None:'),
    ("select options are sent as strings again",
     '            q["options"] = [({"value": o, "label": str(o)} if not isinstance(o, dict) else o) for o in q["options"]]',
     '            q["options"] = list(q["options"])',
     "select options become {value, label} objects; other fields and already-object options pass through untouched",
     '{"value": o, "label": str(o)}'),
    ("the registration skips the normaliser",
     '                       "properties": normalise_properties(_c["properties"])}, 100 + _i)',
     '                       "properties": _c["properties"]}, 100 + _i)',
     "every registration goes through the normaliser and a refusal is returned before any id is looked for",
     'normalise_properties(_c["properties"])'),
    ("the Skill tool is offered again",
     '         "--disallowedTools", "Skill,Task,Agent",',
     '         "--disallowedTools", "Task,Agent",',
     "the Skill tool is withheld, not asked",
     '"--disallowedTools", "Skill,Task,Agent"'),
    # ZAC'S THREE ADDITIONS (2026-09-18): the negative control, the density, the itemised tail
    ("the probe pins its density at 2",
     'sheets, times = _preview_frames(tok, pid, _end or 610, fps=30, density_fps=density_fps, mark=',
     'sheets, times = _preview_frames(tok, pid, _end or 610, fps=30, density_fps=2.0, mark=',
     "the probe takes a density and hands it to the rewatch instrument",
     "density_fps=density_fps, mark=lambda k: marks"),
    ("the plants land before the control reads",
     '    # ── THE CONTROL: the clean timeline. Anything named or touched is a false positive.\n',
     '    _plant()\n    # ── THE CONTROL: the clean timeline. Anything named or touched is a false positive.\n',
     "the control review runs before the plants land",
     "_plant()"),
    ("false positives are declared, not counted",
     '"false_positives": len(ctrl_ops), "ops_whys": ctrl_ops,',
     '"false_positives": 0, "ops_whys": ctrl_ops,',
     "false positives are counted from the control's own ops, not declared",
     '"false_positives": len(ctrl_ops)'),
    ("the probe's cold rule is switched off",
     '"cold": wr > 0.5 * max(1, wr + rd)}',
     '"cold": False}',
     "each review carries the job's cold-write rule and the API's own status",
     'wr > 0.5 * max(1, wr + rd)'),
    ("the export drops its download mark",
     '        if mark: mark("export.download")\n',
     '        pass\n',
     "harness_export marks submit, render, download, upload in that order",
     'mark("export.download")'),
    ("the tail's upload part is not derived",
     '"upload": d("export.download", "export.upload")}',
     '"upload": None}',
     "the export tail is itemised: gate + render + download + upload = the tail",
     '"upload": d("export.download", "export.upload")'),
    ("the rewatch header says 2fps whatever the density",
     'float(_w.get("density_fps") or 2.0), len(_w.get("sheets") or [])',
     '2.0, len(_w.get("sheets") or [])',
     "the rewatch header names the density it was rendered at",
     '_w.get("density_fps")'),
    ("edit() pins the rewatch at 2 fps",
     'fps=float(_rb.get("fps") or 30), density_fps=density_fps,',
     'fps=float(_rb.get("fps") or 30), density_fps=2.0,',
     "a job takes --density-fps and edit() hands it to the rewatch instrument and the run line",
     'density_fps=density_fps'),
    ("a brief file is read and thrown away",
     '        brief = open(brief_file, encoding="utf-8").read().strip()\n',
     '        open(brief_file, encoding="utf-8").read().strip()\n',
     "a brief can come from a file (quoting-safe for the batch)",
     'brief = open(brief_file'),
    # THE BRIEF'S CONSTRAINTS, ENFORCED (Zac, 2026-09-18) — the RED proof Zac named is the second one
    # RE-AIMED 2026-09-19. The old anchor was the pre-multilingual caption regex and had
    # not existed since _CAPTION_WORD was widened, so this mutation replaced nothing and
    # the leg it names went a whole session unproven. Aimed at the RULE now, which cannot
    # drift out from under it the way a spelling can.
    ("the extractor forgets captions",
     '    ("no_captions", True, re.compile(',
     '    ("no_captions_GONE", True, re.compile(',
     "a 'no captions' brief is extracted as a checkable constraint",
     '("no_captions", True, re.compile('),
    ("a caption track no longer violates no captions",
     '    cap_items = [i for i in placed if str(i.get("itemType") or "") == "caption" or _name(i).startswith("caption:")]',
     '    cap_items = []',
     "a 'no captions' brief and a timeline carrying a caption track is a fault naming the track",
     '_name(i).startswith("caption:")]'),
    ("an unreadable caption state passes",
     '                rows.append({"kind": k, "state": cap.get("state") or "ABSENT", "read": read}); faults.append("no captions (brief) UNVERIFIED: %s" % read)',
     '                rows.append({"kind": k, "state": "PASS", "read": read})',
     "a caption read that is ABSENT or FAILED is a fault, not a pass",
     'no captions (brief) UNVERIFIED'),
    ("music is a sound effect",
     '            music = [i for i in placed if str(i.get("itemType") or "") == "audio" and _dur(i) >= 5 * fps]',
     '            music = []',
     "no music: a 30s audio item is a fault; a 1s sound effect is not",
     '_dur(i) >= 5 * fps]'),
    ("the duration ceiling is switched off",
     '            ok = {"<=": end_s <= tgt + 0.5,',
     '            ok = {"<=": True,',
     "duration: at or under 30 fails at 35 and passes at 28; about 45 fails at 50 and passes at 47; exactly 60 passes at 60.4",
     '"<=": end_s <= tgt + 0.5'),
    ("a hidden region is claimed checkable",
     '    ("hide_region", False, re.compile(',
     '    ("hide_region", True, re.compile(',
     "blur/hide a region is reported UNCHECKED, never passed",
     '("hide_region", False'),
    ("the export is honored over a violated constraint",
     '    cf = _hold(2)',
     '    cf = []',
     "the constraint check runs ONCE, at call 2, and its fault is the terminal",
     'cf = _hold(2)'),
    ("a failed read-back exports anyway",
     '    if cf or rb:\n        tm["terminal"] = {"kind": "READBACK FAILED", "at": 2,',
     '    if False:\n        tm["terminal"] = {"kind": "READBACK FAILED", "at": 2,',
     "A VIOLATED CONSTRAINT AT CALL 2 IS TERMINAL AND REFUNDED — there is no third call to fix it in",
     'if cf or rb:'),
    ("the rewatch drops the constraint faults",
     '        _faults = _faults + ["BRIEF CONSTRAINT VIOLATED — %s" % f for f in _cf_rw]',
     '        _faults = _faults',
     "the rewatch hands constraint violations to the next turn as faults",
     '"BRIEF CONSTRAINT VIOLATED — %s" % f for f in _cf_rw'),
    ("the machine runs without the verify hook",
     '    _tm = run_two_calls(_invoke, _rewatch, _first_message, t0=t0, verify=_verify,',
     '    _tm = run_two_calls(_invoke, _rewatch, _first_message, t0=t0,',
     "edit() hands the constraint check to the turn machine",
     'verify=_verify,'),
    ("the agent is not told",
     '        if constraints and constraint_prompt(constraints):\n            blocks.append({"type": "text", "text": constraint_prompt(constraints)})',
     '        if False:\n            blocks.append({"type": "text", "text": constraint_prompt(constraints)})',
     "the first message tells the agent the constraints, after the inventory and the face",
     'if constraints and constraint_prompt(constraints):'),
    ("the API's own caption count is ignored",
     '    if isinstance(r.get("returned"), int):\n        return {"state": "MEASURED", "cards": int(r["returned"]), "why": "from the API\'s `returned` count"}',
     '    if False:\n        return {"state": "MEASURED", "cards": int(r["returned"]), "why": "from the API\'s `returned` count"}',
     "caption_cards: MEASURED from a list or the API's count, ABSENT with the keys, FAILED on an error",
     'isinstance(r.get("returned"), int)'),
    ("the no-watch arm starts a fresh session every turn again",
     '        if no_watch and n == 1 and _res.get("session_id"):\n            _run_sid["sid"] = str(_res.get("session_id"))',
     '        if False:\n            _run_sid["sid"] = str(_res.get("session_id"))',
     "no-watch: turn 1 creates the session cold and every later turn resumes it; the record says which and whether it resumed",
     '_run_sid["sid"] = str(_res.get("session_id"))'),
    ("a contaminated reused stage runs anyway",
     '        if _stage.get("priorItems") is None or len(_stage.get("priorItems") or []) > 0:',
     '        if False:',
     "a reused stage whose timeline holds items, or cannot be read, is a CONTAMINATED ARM terminal before any model call",
     'len(_stage.get("priorItems") or []) > 0'),
    ("Bash comes back into the agent's tool list", 
     '             "--allowedTools", _sel,\n             "--tools", _sel,',
     '             "--allowedTools", _sel + ",Bash",\n             "--tools", _sel + ",Bash",',
     "THE GATE: no builtin is named on any turn — Bash above all (a Bash call to load a disallowed skill killed a run, 2026-09-18)",
     '"--allowedTools", _sel,'),
    ("the read tools come back into the agent's tool list",
     'AGENT_TOOLS = ["edit_item", "edit_captions", "finish"]',
     'AGENT_TOOLS = ["edit_item", "edit_captions", "finish", "read_project"]',
     "THE GATE: no read tool is named on any turn — the harness reads the timeline back and serves it",
     'AGENT_TOOLS = ["edit_item", "edit_captions", "finish"]'),
    ("the shim re-advertises what the flags removed",
     '"MCP_SHIM_ALLOW": ",".join(AGENT_TOOLS),',
     '"MCP_SHIM_ALLOW": ",".join(NEEDED_TOOLS),',
     "the shim is told the same list, so tools/list cannot re-advertise what the flags removed",
     '"MCP_SHIM_ALLOW": ",".join(AGENT_TOOLS),'),
    ("a capped turn is applied instead of ending the run",
     '        if r.get("stop_reason") == "max_tokens":',
     '        if False:',
     "a turn that hits the cap is a NAMED terminal and its truncated tool call is never applied",
     'r.get("stop_reason") == "max_tokens"'),
    ("the cap is guessed instead of derived",
     'OUTPUT_CAP_TOKENS = 2 * 1108',
     'OUTPUT_CAP_TOKENS = 8000',
     "the cap's derivation is recorded from a measured full edit, not guessed (held, not applied)",
     'OUTPUT_CAP_TOKENS = 2 * 1108'),
    ("the held cap is applied to the body anyway",
     '        _px.MAX_OUTPUT_TOKENS = 0',
     '        _px.MAX_OUTPUT_TOKENS = OUTPUT_CAP_TOKENS',
     "NO cap is applied to the body while thinking is uncontrolled — the proxy can, and edit() passes 0",
     '_px.MAX_OUTPUT_TOKENS = 0'),
    ("the diet stops bounding the why",
     '"Every `why` is TWELVE WORDS OR FEWER. Write no prose, no plan, no summary, no "',
     '"Say as much as you like about each op. "',
     "the paragraph states the diet: a why under 12 words, no prose, payloads carrying only what the harness executes",
     "THE DIET, and it is the reason a run times out"),
    ("a raised run bound stops being recorded",
     '"run_bound_s": _bound_s, "run_bound_raised": _bound_s != RUN_TIMEOUT_S,',
     '"run_bound_s": _bound_s, "run_bound_raised": False,',
     "a widened run bound is a PARAMETER, defaults to the law, and the record says when it was raised",
     '"run_bound_raised": _bound_s != RUN_TIMEOUT_S'),
    ("the tool block is assumed identical instead of hashed",
     '        _shas = {x["sha"] for x in _tools_by_call if x.get("sha")}\n        _tools_same = (len(_shas) == 1) if _tools_by_call else None',
     '        _shas = set()\n        _tools_same = True',
     "the tool block is proven identical across calls from the proxy's own hash, not from the flags",
     '_tools_same = (len(_shas) == 1) if _tools_by_call else None'),
    ("the response's thinking blocks stop being counted",
     '                _think_by_call[str(_rs.get("turn"))] = {"deltas": _rs.get("thinking_deltas"),',
     '                _think_by_call[str(_rs.get("turn"))] = {"deltas": 0,',
     "the response's thinking blocks are read per call and reported beside the output they are billed inside",
     '"deltas": _rs.get("thinking_deltas")'),
    ("a text-only turn is applied instead of refused",
     '        if not r.get("killed") and not (r.get("tool_calls") or []) and (r.get("text") or "").strip():',
     '        if False:',
     "A TURN THAT RETURNS TEXT ONLY IS REFUSED BEFORE ANYTHING IS APPLIED (Haiku wrote its edit inside a ```json fence and called nothing)",
     'not (r.get("tool_calls") or []) and (r.get("text") or "").strip()'),
    ("the verdict goes back to being a word in prose",
     '    fin2 = _finish_verdict(r2.get("tool_calls"))',
     '    fin2 = "export" if _says(r2.get("text"), "export", "clean", "ship") else None',
     "a call 2 that calls some other tool and SAYS export is NO VERDICT, not an export",
     'fin2 = _finish_verdict(r2.get("tool_calls"))'),
    ("the proxy stops forcing a tool call",
     '    if TOOL_CHOICE_ANY and body.get("tools"):\n        body["tool_choice"] = {"type": "any"}',
     '    if False:\n        body["tool_choice"] = {"type": "any"}',
     "the proxy sets tool_choice any on a body that has tools, leaves one without tools alone, and only when armed",
     'if TOOL_CHOICE_ANY and body.get("tools"):'),
    ("the shim stops serving finish",
     '        if not ALLOW or "finish" in ALLOW:\n            kept.append(FINISH_TOOL)',
     '        if False:\n            kept.append(FINISH_TOOL)',
     "the shim ADVERTISES `finish` and serves it itself, refusing a verdict that is not clean or export",
     'kept.append(FINISH_TOOL)'),
    ("the canonical arm stops being the default",
     'CANONICAL_EFFORT = "low"',
     'CANONICAL_EFFORT = "high"',
     "Sonnet canonical — thinking disabled, effort low — is the DEFAULT for a job, and the ping carries the same pair",
     'CANONICAL_EFFORT = "low"'),
    ("the proxy's connection threads stop being daemons",
     '    srv.daemon_threads = True',
     '    srv.daemon_threads = False',
     "the proxy's server marks its connection threads as daemons, so a tunnel cannot outlive the process",
     'srv.daemon_threads = True'),
    ("a lingering container stops being a defect",
     '    _lingered = _after_export_s is not None and _after_export_s > EXPORT_TO_EXIT_BUDGET_S',
     '    _lingered = False',
     "a container that outlives its export past the budget is a LEDGERED DEFECT with an owner page",
     '_after_export_s > EXPORT_TO_EXIT_BUDGET_S'),
    ("an empty catalogue read goes back to reading as MEASURED",
     '    if not ids:\n        return [], "ABSENT",',
     '    if not ids:\n        return [], "MEASURED",',
     "AN EMPTY CATALOGUE READ IS ABSENT AND NAMES THE KEYS IT SAW — never MEASURED with an empty list",
     'if not ids:'),
    ("the reader stops walking nested envelopes",
     '            for k, v in node.items():\n                if k.startswith("_"):\n                    continue\n                _walk(v, "%s.%s" % (path, k) if path else k)',
     '            for k, v in node.items():\n                if k.startswith("_"):\n                    continue',
     "library_ids finds every id however the envelope nests it, and names the key it used",
     'for k, v in node.items():'),
    ("the reader stops naming the key it used",
     '    why = "%d id(s) under %s%s" % (len(ids), ", ".join(sorted(set(used))[:3]),',
     '    why = "%d id(s)%s%s" % (len(ids), "",',
     "library_ids finds every id however the envelope nests it, and names the key it used",
     'id(s) under %s%s'),
    ("the caption word goes back to English only",
     '_CAPTION_WORD = (r"(?:captions?|subtitles?|subs|legendas?|subt[ií]tulos?|sous-titres?|untertitel|"',
     '_CAPTION_WORD = (r"(?:captions?|subtitles?|subs|"',
     "a caption constraint is read in the languages this corpus actually contains, not only English",
     'legendas?|subt[ií]tulos?'),
    ("an only-brief stops being a constraint",
     '    ("scope_only", True, re.compile(',
     '    ("scope_only", False, re.compile(',
     "an ONLY / do-not-alter brief is a CHECKABLE scope constraint naming the licensed family",
     '("scope_only", True'),
    ("an unasked op stops failing a captions-only brief",
     '            extra = [i for i in placed if not (allowed and _fam_of(i) == allowed)]',
     '            extra = []',
     "ONE unasked op fails a captions-only brief, and the fault names the item and its family",
     'extra = [i for i in placed if not (allowed and _fam_of(i) == allowed)]'),
    # ---- THE `only` REWRITE (2026-09-19). Each leg driven red against the thing it names. ----
    ("the ask guard goes away, and a category-scoped only becomes a licence again",
     '                if fam and (_asks - {fam}):',
     '                if fam and False:',
     "a category-scoped `only` never becomes a whole-timeline licence",
     'if fam and (_asks - {fam}):'),
    ("no_cuts is no longer extracted at all",
     '    ("no_cuts", True, re.compile(',
     '    ("no_cuts_GONE", True, re.compile(',
     "`one continuous take` is a checkable no-cuts constraint, and a cut-density note is not",
     '("no_cuts", True, re.compile('),
    ("a cut-density note impersonates a ban again",
     '            if kind == "no_cuts" and "cut" in _brief_asks(text):\n                continue\n',
     '',
     "`one continuous take` is a checkable no-cuts constraint, and a cut-density note is not",
     'if kind == "no_cuts" and "cut" in _brief_asks(text):'),
    ("the no-cuts check stops counting video items",
     '            elif len(vids) > 1:',
     '            elif False:',
     "no-cuts passes on one video item, fails on two, and an unreadable timeline is ABSENT not PASS",
     'elif len(vids) > 1:'),
    ("an unreadable timeline reads as a clean no-cuts pass",
     '            if not vids:',
     '            if False:',
     "no-cuts passes on one video item, fails on two, and an unreadable timeline is ABSENT not PASS",
     'if not vids:'),
    ("the checker loses the no_cuts branch while the extractor keeps emitting it",
     '        elif k == "no_cuts":',
     '        elif k == "no_cuts_UNREACHABLE":',
     "every checkable constraint kind has a branch in the checker",
     'elif k == "no_cuts":'),
    ("the extractor emits a family the checker cannot classify",
     '"sfx": "sound",\n                       "music": "sound"}',
     '"sfx": "sound"}',
     "every family the extractor can emit is one the read-back checker can classify",
     '"music": "sound"}'),
    ("a checkable kind loses its plain-words meaning",
     '                       "no_cuts": "the source stays ONE video item',
     '                       "no_cuts_GONE": "the source stays ONE video item',
     "every checkable constraint kind is stated to the agent in words, never as its kind name",
     '"no_cuts": "the source stays ONE video item'),
    ("the licensed family is never substituted into the sentence",
     '        elif c["kind"] == "scope_only":\n            _a = (c.get("value") or {}).get("allowed")',
     '        elif c["kind"] == "scope_only_GONE":\n            _a = (c.get("value") or {}).get("allowed")',
     "the rendered constraint block names the licensed family and leaves no placeholder unfilled",
     'elif c["kind"] == "scope_only":'),
    ("an empty before-read goes back to reading as a measured empty timeline",
     '    if not items:\n        return {"state": "ABSENT"',
     '    if False:\n        return {"state": "ABSENT"',
     "an empty read is ABSENT and an errored read is FAILED — neither reads as nothing was touched",
     '    if not items:'),
    ("the before-timeline stops deriving a missing duration",
     '        if dur is None and frm is not None and to is not None:',
     '        if False:',
     "dur is derived from the frame range when the item does not carry it",
     'if dur is None and frm is not None and to is not None:'),
    ("the before-timeline never reaches the record",
     '    out["before_timeline"] = _state.get("before_timeline") or {',
     '    out["before_timeline_UNUSED"] = _state.get("before_timeline") or {',
     "the before-timeline is captured BEFORE turn 1 and reaches the record",
     'out["before_timeline"] = _state.get("before_timeline")'),
    ("an identical pair is delivered anyway",
     '    if not prof["differing"]:',
     '    if False:',
     "a pixel-identical pair is IDENTICAL and is never delivered",
     'if not prof["differing"]:'),
    ("an unreadable comparison reads as a proven pair",
     '    if prof["state"] != "MEASURED":',
     '    if False:',
     "an unread or absent comparison is ABSENT or FAILED, never a proven pair",
     'if prof["state"] != "MEASURED":'),
    ("the difference gate grows a threshold",
     '        if float(d.max()) > 0:',
     '        if float(d.mean()) > 2.0:',
     "ONE differing pixel is enough to make it a pair, with no threshold to calibrate",
     'if float(d.max()) > 0:'),
    ("the container is given the emitter and could re-emit",
     '    .add_local_dir(os.path.join(_HERE, "port", "build"), "/craft/port", copy=True)',
     '    .add_local_dir(os.path.join(_HERE, "port", "bodies"), "/craft/port", copy=True)',
     "only the BUILT blobs are mounted, and the component is read from them",
     'os.path.join(_HERE, "port", "build"), "/craft/port"'),
    ("the labels stop naming whose default it is",
     '    return ("THEIRS — %s: their default',
     '    return ("THEIRS — %s: a zoom',
     "the pair is labelled honestly on both sides, naming each component",
     'THEIRS — %s: their default'),
    ("a one-sided pair is composed anyway",
     '    if not top_path or not bottom_path:',
     '    if False:',
     "a one-sided pair is ABSENT and writes nothing",
     'if not top_path or not bottom_path:'),
    ("the contract check stops seeing AbsoluteFill",
     '    if re.search(r"\\bAbsoluteFill\\b", stripped):',
     '    if False:',
     "each of the four refusal classes is caught, and a COMMENT is not code",
     'if re.search(r"\\bAbsoluteFill\\b", stripped):'),
    ("the contract check reads comments as code again",
     '    stripped = re.sub(r"/\\*.*?\\*/", "", code, flags=re.S)',
     '    stripped = code',
     "every component this harness can send satisfies the contract we measured",
     'stripped = re.sub(r"/\\*.*?\\*/", "", code, flags=re.S)'),
    ("top-level constants stop being refused",
     '    if extra:',
     '    if False:',
     "each of the four refusal classes is caught, and a COMMENT is not code",
     '    if extra:'),
    ("a dirty control stops confounding the pair",
     '        if ctrl["differing"]:',
     '        if False:',
     "a pair whose CONTROL differs is CONFOUNDED and is never delivered",
     'if ctrl["differing"]:'),
    ("the two arms go back to separate projects",
     '    stage = prestage(tok, "", controls={}, source_path="/work/source.mp4",\n                     want_components=set(), titles=[])\n    pid, base, src_asset = stage["projectId"], stage.get("baseItemId"), stage.get("sourceAssetId")\n    out["project"] = pid',
     '    stage = prestage(tok, "", controls={}, source_path="/work/source.mp4",\n                     want_components=set(), titles=[])\n    stage = prestage(tok, "", controls={}, source_path="/work/source.mp4",\n                     want_components=set(), titles=[])\n    pid, base, src_asset = stage["projectId"], stage.get("baseItemId"), stage.get("sourceAssetId")\n    out["project"] = pid',
     "both arms share one project, one upload and one timeline, placed in sequence",
     'out["project"] = pid'),
    ("a name goes undefined on disk",
     '    def place_theirs(pid, base, _src):',
     '    def place_theirs_RENAMED(pid, base, _src):',
     "the WORKING tree carries no undefined name and no shadowed definition",
     'def place_theirs(pid, base, _src):'),
    ("a built component loses its property table",
     '    "StagedPush": [\n        {"key": "clip", "label": "Clip", "type": "video", "defaultValue": ""},',
     '    "StagedPush_GONE": [\n        {"key": "clip", "label": "Clip", "type": "video", "defaultValue": ""},',
     "every built component has a property table, and the table has no orphans",
     '    "StagedPush": ['),
    ("the comparison goes back to positional",
     '    common = sorted(set(a or {}) & set(b or {}))',
     '    common = sorted(set(a or {}) | set(b or {}))',
     "only frames present on BOTH sides are compared, and the rest are named",
     'common = sorted(set(a or {}) & set(b or {}))'),
    ("the delete goes back to a key edit_item ignores",
     '{"projectId": pid, "deletes": [{"itemId": item_id}]}',
     '{"projectId": pid, "removes": [item_id]}',
     "the arm is deleted with the key edit_item accepts, and the read-back proves it",
     '"deletes": [{"itemId": item_id}]'),
    ("the pair goes back to a grid over the whole timeline",
     '        ctrl, miss_c = frames_at(tok, pid, ctrl_frames, "/work/%s_control" % label)',
     '        ctrl, miss_c = _preview_frames(tok, pid, from_frame), []',
     "the pair samples a control window and a test window by frame number",
     'frames_at(tok, pid, ctrl_frames'),
    ('an ignored key stops being caught',
     '    if unknown:',
     '    if False:',
     'an ignored key is UNKNOWN_OP, and a 200 that echoes nothing is NONE',
     '    if unknown:'),
    ('a short echo stops being partial',
     '    if short:',
     '    if False:',
     'fewer ids than ops sent is PARTIAL, a matching echo is APPLIED, and a silent response is UNREADABLE',
     '    if short:'),
    ('the delete goes back to the shape ChatCut refuses',
     '{"projectId": pid, "deletes": [{"id": item_id}]}',
     '{"projectId": pid, "deletes": [{"itemId": item_id}]}',
     'every delete uses the key the ChatCut schema requires, and none uses the refused one',
     '"deletes": [{"id": item_id}]'),
    ('the gone check goes back to a bare membership test',
     '            _norm = lambda x: str(x or "").replace("-", "").lower()',
     '            _norm = lambda x: str(x or "")',
     'an echo id is matched against read-back UUIDs by prefix, so `gone` can actually fail',
     '_norm = lambda x: str(x or "").replace("-", "").lower()'),
    ('a refusal it does not recognise goes back to None',
     '    return "no assetId, and the response said: %s" % txt[:900]',
     '    return None',
     'a refusal always carries words, whatever shape the response took',
     'return "no assetId, and the response said: %s" % txt[:900]'),
    ('an empty response stops naming its keys',
     '        return ("the response carried no text at all; keys present: %s"\n                % sorted(envelope)[:12])',
     '        return None',
     'and the keys are named when there is no text to quote',
     'the response carried no text at all; keys present'),
    ('the declared-but-unused rule goes away',
     '        if unused:',
     '        if False:',
     'a property declared and never read is caught, and so is a read that was never declared',
     '        if unused:'),
    ('the undeclared-read rule goes away',
     '        if undeclared:',
     '        if False:',
     'a property declared and never read is caught, and so is a read that was never declared',
     '        if undeclared:'),
    ('a differing layer at rest stops being a fault',
     '    if prof["differing"]:\n        return {"state": "DIFFERS"',
     '    if False:\n        return {"state": "DIFFERS"',
     'a layer that is a no-op at rest is IDENTICAL, and ONE differing pixel is a FAULT',
     'return {"state": "DIFFERS"'),
    ('the rest frames move outside the span',
     '    probe_frames = [from_frame + int(round(dur_frames * i / 8.0)) for i in range(9)]',
     '    probe_frames = [int(round(from_frame * i / 9.0)) for i in range(9)]',
     'the rest frames sit INSIDE the span, where the component is actually placed',
     'probe_frames = [from_frame + int(round(dur_frames * i / 8.0)) for i in range(9)]'),
    ('the correction becomes a plain brightness multiply',
     '    c = 1.0 + 2.0 * k / 255.0\n    return "brightness(%.6f) contrast(%.6f)" % (1.0 / c, c)',
     '    return "brightness(%.6f)" % (1.0 - k / 255.0)',
     'the correction is an exact affine: slope 1, intercept minus k levels',
     'return "brightness(%.6f) contrast(%.6f)" % (1.0 / c, c)'),
    ('the tolerance stops being per channel',
     '    worst = max(abs(x) for x in residual["rgb"])',
     '    worst = abs(sum(residual["rgb"]) / 3.0)',
     'the gate passes only when every channel is inside the tolerance',
     'worst = max(abs(x) for x in residual["rgb"])'),
    ('a ported component stops taking the calibration',
     '  const correct = props.correct || "";',
     '  const correct = "";',
     'SmoothPush takes the rest calibration as a property and hard-codes no level',
     'const correct = props.correct || "";'),
    ('drift stops being reported',
     '        if drift > drift_tol:',
     '        if False:',
     "drift past the tolerance is REPORTED, never re-measured on the job's path",
     'if drift > drift_tol:'),
    ('a missing calibration stops being named',
     '        return {"action": "ABSENT", "age_s": None,',
     '        return {"action": "USE", "age_s": None,',
     'with no calibration at all the correction is NOT applied and the run says so',
     '"action": "ABSENT", "age_s": None,'),
    ('the library loses the text-overlay family again',
     '"text overlay": [\n  "TornPaper",',
     '"text overlay_GONE": [\n  "TornPaper",',
     'the library carries the whole text-overlay family, and the count is corrected with a why',
     '"text overlay"'),
    ('a variant loses its size dial',
     '        {"key": "size", "label": "Size", "type": "select", "defaultValue": "medium",\n         "options": ["small", "medium", "large", "xlarge"]},\n        {"key": "position", "label": "Position", "type": "select", "defaultValue": "middle",\n         "options": ["top", "middle", "bottom"]},\n        {"key": "textColor", "label": "Text colour", "type": "color", "defaultValue": "#FFFFFF"},\n        {"key": "accentColor", "label": "Accent colour", "type": "color", "defaultValue": "#C8551F"},\n    ],\n    "QuoteCard"',
     '        {"key": "position", "label": "Position", "type": "select", "defaultValue": "middle",\n         "options": ["top", "middle", "bottom"]},\n        {"key": "textColor", "label": "Text colour", "type": "color", "defaultValue": "#FFFFFF"},\n        {"key": "accentColor", "label": "Accent colour", "type": "color", "defaultValue": "#C8551F"},\n    ],\n    "QuoteCard"',
     'TornPaper is built, contract-clean, and exposes size and position as dials',
     '"QuoteCard"'),
    ("a variant's default drifts off what the references measure",
     '{"key": "quote", "label": "Quote", "type": "text", "defaultValue": ""},\n        {"key": "attribution", "label": "Attribution (no em dash \u2014 the card adds it)", "type": "text", "defaultValue": ""},\n        {"key": "size", "label": "Size", "type": "select", "defaultValue": "medium",',
     '{"key": "quote", "label": "Quote", "type": "text", "defaultValue": ""},\n        {"key": "attribution", "label": "Attribution (no em dash \u2014 the card adds it)", "type": "text", "defaultValue": ""},\n        {"key": "size", "label": "Size", "type": "select", "defaultValue": "large",',
     "every variant defaults to medium, and to middle except the lower third",
     '{"key": "quote", "label": "Quote"'),
    ('a malformed entry stops being a fault',
     '        if not bits[0].strip():\n            out.append("%s entry %d (%r) has no %s"',
     '        if False:\n            out.append("%s entry %d (%r) has no %s"',
     'a malformed packed entry is named, and a well-formed one is not',
     'if not bits[0].strip():\n            out.append'),
    ('an over-long list goes back to being silently dropped',
     '    if kept > spec["max_items"]:',
     '    if False:',
     'an entry count past what the component renders is named rather than dropped',
     'if kept > spec["max_items"]:'),
    ('the read-back stops withholding on an unreadable property',
     '        _pf_rw = component_faults(_items)',
     '        _pf_rw = []',
     'the component renders no error text, and the fault reaches the rewatch AND the read-back',
     '_pf_rw = component_faults(_items)'),
    ('the component draws its own error into the frame again',
     '          transform: "rotate(" + n.rotation + "deg) translateY(" + ((1 - ease) * (26 + i * 10)) + "px)" }}>\n          {n.text}\n        </div>))}',
     '          transform: "rotate(" + n.rotation + "deg) translateY(" + ((1 - ease) * (26 + i * 10)) + "px)" }}>\n          {n.text}\n        </div>))}\n      <div>{"malformed"}</div>',
     'the component renders no error text, and the fault reaches the rewatch AND the read-back',
     '{n.text}'),
    ('an unused binding stops being caught',
     '        if not re.search(r"\\\\b%s\\\\b" % re.escape(nm), elsewhere):',
     '        if False:',
     'a property read into a binding that is never USED is caught',
     'if not re.search(r"\\\\b%s\\\\b" % re.escape(nm), elsewhere):'),
    ('uses are counted inside the declaration again',
     '        elsewhere = stripped[:m.start()] + stripped[m.end():]',
     '        elsewhere = stripped',
     'a property read into a binding that is never USED is caught',
     'elsewhere = stripped[:m.start()] + stripped[m.end():]'),
    ('a seam-feeding reader goes back to a bare list',
     '        return {"state": "ABSENT", "faults": [], "checked": 0,',
     '        return {"state": "MEASURED", "faults": [], "checked": 0,',
     'every seam-feeding reader answers ABSENT on a source missing the key it reads',
     '"state": "ABSENT", "faults": [], "checked": 0,'),
    ('the prose parser stops reading the effective block',
     '    m = re.search(r"(?:Motion Graphic )?Effective Props:\\\\s*\\\\n((?:\\\\s+\\\\S+=.*\\\\n?)+)", txt)',
     '    m = None if True else re.search(r"x", txt)',
     "a placed item's properties are parsed out of inspect_item's prose, defaults included",
     'Effective Props:'),
    ('a property site goes back to walking the envelope for a string key',
     '                _pr = item_props_from_inspect(_ii)\n                _pv = _pr["props"] if _pr["state"] == "MEASURED" else None',
     '                _pv = _deep_find(_ii, "propertyOverrides")',
     'no property site walks the envelope for a propertyOverrides key any more',
     '_pr = item_props_from_inspect(_ii)'),
    ('self-comparison goes back to answering zero',
     '    if list(a_paths) == list(b_paths):',
     '    if False:',
     'a comparison whose two sides name the same files is a FAULT, not a zero',
     'if list(a_paths) == list(b_paths):'),
    ('placements share a frame directory again',
     '        f, _ms = frames_at(tok, pid, probe,\n                           "/work/tf_%s" % re.sub(r"[^A-Za-z0-9]+", "_", "%s_%s" % (name, label)))',
     '        f, _ms = frames_at(tok, pid, probe, "/work/tf_%s" % name)',
     'each placement writes its frames to its own directory',
     '"%s_%s" % (name, label)'),
    ('a failed transcript reads as silence again',
     '    if st == "MEASURED":\n        if n:',
     '    if True:\n        if n:',
     'a transcript that did NOT complete is `other`, never no-speech, and carries why',
     'if st == "MEASURED":'),
    ('the route stops reaching the record',
     '    out["route"] = run_route(_beats, _beats_box.get("state"), _beats_box.get("why"))',
     '    out["route_UNUSED"] = run_route(_beats, _beats_box.get("state"), _beats_box.get("why"))',
     "the route travels on the record, computed from the beats' own state",
     'out["route"] = run_route(_beats'),
    ('the face check goes back to condemning any contact',
     '    if f > tol:',
     '    if f > 0.0:',
     'a card centred on the face FAULTS and text clear of it does NOT',
     '    if f > tol:'),
    ('the face box loses its horizontal term',
     '    return {"state": "MEASURED", "box": [cx - h, cy - h, cx + h, cy + h],',
     '    return {"state": "MEASURED", "box": [0.0, cy - h, frame_w, cy + h],',
     "the face box comes from the detector's extent, or a named window round the centre",
     '"box": [cx - h, cy - h, cx + h, cy + h]'),
    ('missing geometry reads as a pass',
     '        return {"state": "ABSENT", "fraction": None,\n                "why": "one of the two boxes is missing — nothing is claimed"}',
     '        return {"state": "MEASURED", "fraction": 0.0,\n                "why": "one of the two boxes is missing — nothing is claimed"}',
     'missing geometry is ABSENT, never a pass',
     'one of the two boxes is missing'),
    ("an unreadable brief goes back to reading as clean",
     '    if not out and (_nonascii > max(3, 0.02 * max(1, len(text)))):',
     '    if False:',
     "a brief this extractor cannot read is UNCHECKED, never a clean read",
     '_nonascii > max(3, 0.02 * max(1, len(text)))'),
]


SMOKE_TIMEOUT_S = 180


def run_smoke():
    """-> (rc, output). A HANG IS A HARNESS FAILURE, NOT A RED. Without this bound one mutant ran for
    2h20m and produced nothing (2026-09-19): a lingering proxy connection thread kept the smoke alive
    after it had printed its verdict, and `subprocess.run` waited on it. rc 124 is reserved for the
    timeout so a caller cannot read it as the smoke's own exit code."""
    try:
        r = subprocess.run([sys.executable, SMOKE], capture_output=True, text=True, timeout=SMOKE_TIMEOUT_S)
    except subprocess.TimeoutExpired as e:                        # noqa: PERF203
        out = (e.stdout or b"").decode("utf-8", "replace") if isinstance(e.stdout, bytes) else (e.stdout or "")
        return 124, out + "\n*** HARNESS: the smoke did not exit within %ds — killed. A hang is not a result." % SMOKE_TIMEOUT_S
    return r.returncode, (r.stdout or "") + (r.stderr or "")


def leg_failed(out, leg):
    return re.search(r"^\s+%s\s+FAIL\s*$" % re.escape(leg), out, re.M) is not None


def main():
    # THE CHECKED SURFACE IS NO LONGER ONLY PYTHON. The library's count lives in a
    # JSON file and the ported components are JSX built blobs; a mutation aimed at
    # either would have found its anchor in no source and reported VACUOUS — a leg
    # that cannot be driven red is not yet a check, which is this file's whole point.
    _PY = ("chatcut_job_app.py", "chatcut_gate.py", "turn_clock.py", "mcp_shim.py", "api_proxy.py")
    _OTHER = tuple(t for t in (["library_73.json"] + sorted(glob.glob("port/build/*.jsx"))
                               + sorted(glob.glob("port/bodies/*.jsx"))) if os.path.exists(t))
    srcs = {t: io.open(t, encoding="utf-8").read() for t in _PY + _OTHER}

    rc, out = run_smoke()
    if rc != 0:
        print("HARNESS FAILURE: the unmutated smoke is %s (rc=%d)\n%s"
              % ("HUNG" if rc == 124 else "not green", rc, out[-1200:]))
        sys.exit(2)

    red, bad = 0, []
    for label, anchor, repl, leg, pre in MUTATIONS:
        TARGET = next((t for t in list(_PY[1:]) + list(_OTHER) if anchor in srcs[t]), "chatcut_job_app.py")
        src = srcs[TARGET]
        if pre is not None and pre not in src:
            bad.append("VACUOUS: %s — %r absent from the source" % (label, pre))
            print("  [VACUOUS] %s" % label)
            continue
        mode, mutant = RA.apply_one(src, anchor, repl)
        if mutant is None:
            bad.append("HARNESS FAILURE: %s — anchor %s" % (label, mode))
            print("  [ANCHOR %s] %s" % (mode, label))
            continue
        # PARSE-CHECK IN THE TARGET'S OWN LANGUAGE. ast.parse on a JSON or JSX
        # mutant would fail for the wrong reason and report a harness failure where
        # the mutation was fine.
        try:
            if TARGET.endswith(".py"):
                ast.parse(mutant)
            elif TARGET.endswith(".json"):
                json.loads(mutant)
        except (SyntaxError, ValueError) as e:
            bad.append("HARNESS FAILURE: %s — will not parse: %s" % (label, e))
            print("  [UNPARSEABLE] %s" % label)
            continue
        io.open(TARGET, "w", encoding="utf-8").write(mutant)
        try:
            rc2, out2 = run_smoke()
        finally:
            io.open(TARGET, "w", encoding="utf-8").write(src)
        hit = leg_failed(out2, leg)
        if rc2 != 0 and hit:
            red += 1
            print("  [RED]  %-44s (%s) -> %r failed" % (label, mode, leg))
        else:
            bad.append("NOT RED: %s — rc=%d leg_failed=%s" % (label, rc2, hit))
            print("  [NOT RED] %-42s rc=%d leg_failed=%s" % (label, rc2, hit))

    for _t, _s in srcs.items():
        if io.open(_t, encoding="utf-8").read() != _s:
            print("\nRESIDUE: %s left MUTATED — restoring" % _t)
            io.open(_t, "w", encoding="utf-8").write(_s)
            bad.append("RESIDUE: %s did not match the pre-sweep source" % _t)

    print("\n%d/%d RED-proven" % (red, len(MUTATIONS)))
    for b in bad:
        print("  " + b)
    sys.exit(0 if red and red == len(MUTATIONS) and not bad else 1)


if __name__ == "__main__":
    main()
